{
    "Open image": "Deschidere imagine",
    "Save frame": "Salvare segmentare",
    "Save current polygon": "Salvare poligon/contur curent",
    "Delete last vertex": "Sterge ultimul vertex",
    "Delete current polygon": "Sterge poligon curent",
    "Send to back": "Fundal",
    "Undo polygon": "Sterge poligon salvat",
    "Draw class": "Clasa de desenat",
    "land": "câmpie",
    "forest": "pădure",
    "residential": "clădiri",
    "haystack": "căpițe",
    "road": "drum",
    "church": "biserică",
    "cars": "mașină",
    "water": "apă",
    "sky": "cer",
    "hill": "deal",
    "person": "persoană",
    "fence": "gard",
    "Image segmentation": "Segmentare imagini",
    "Segment image": "Segmentează imagine",
    "Edit segmented image": "Editează imagine segmentată",
    "Cancel": "Renunță",
    "Select operation": "Selectează operație",
    "Previous polygon": "Poligon precedent",
    "Next polygon": "Poligon următor",
    "Back to segmentation": "Înapoi la cadru",
    "Change class": "Schimbă clasa",
    "segment": "segmentare",
    "edit": "editare",
    "Previous segmentation": "Segmentare anterioară",
    "Next":"Următor",
    "Previous":"Precendent",
    "Hide seg":" Ascunde Seg"
}
