{
    "Open image": "Open image",
    "Save frame": "Save frame",
    "Save current polygon": "Save current polygon",
    "Delete last vertex": "Delete last vertex",
    "Delete current polygon": "Delete current polygon",
    "Send to back": "Send to back",
    "Undo polygon": "Undo polygon",
    "Draw class": "Draw class",
    "land": "land",
    "forest": "forest",
    "residential": "residential",
    "haystack": "haystack",
    "road": "road",
    "church": "church",
    "cars": "cars",
    "water": "water",
    "sky": "sky",
    "hill": "hill",
    "person": "person",
    "fence": "fence",
    "Image segmentation": "Image segmentation",
    "Segment image": "Segment image",
    "Edit segmented image": "Edit segmented image",
    "Cancel": "Cancel",
    "Select operation": "Select operation",
    "Previous polygon": "Previous polygon",
    "Next polygon": "Next polygon",
    "Back to segmentation": "Back to segmentation",
    "Change class": "Change class",
    "segment": "segment",
    "edit": "edit",
    "Previous segmentation": "Previous segmentation",
    "Next":"Next",
    "Previous":"Previous",
    "Hide seg":"Hide seg"
}
